import type { Candidate } from "../../types/candidates";

export const candidateColumns = [
  "Candidate",
  "Uni",
  "Major",
  "GPA",
  "Status",
  "Score",
  "Nominated",
];

export const candidateData: Candidate[] = [
  {
    id: "1",
    name: "Mohammed Khalil",
    email: "mohammed.khalil@aucegypt.edu",
    university: "The American University in Cairo",
    major: "Computer Science",
    gpa: 3.78,
    status: { status: "Nominated" },
    score: 91,
    isNominated: true,
    videoStatus: { status: "Pass" },
    recommendation: { status: "Strongly Recommended" },
    phone: "010-0000-0001",
    trackPreference: "Software Engineering",
    internships: [],
  },
  {
    id: "2",
    name: "Laila Fathy",
    email: "laila.fathy@cu.edu.eg",
    university: "Cairo University",
    major: "Electrical Engineering",
    gpa: 3.42,
    status: { status: "Evaluated" },
    score: 76,
    isNominated: false,
    videoStatus: { status: "Pass" },
    recommendation: { status: "Recommended" },
    phone: "010-0000-0002",
    trackPreference: "Electrical Systems",
    internships: [],
  },
  {
    id: "3",
    name: "Youssef Adel",
    email: "youssef.adel@asu.edu.eg",
    university: "Ain Shams University",
    major: "Mechanical Engineering",
    gpa: 3.15,
    status: { status: "Rejected" },
    score: 62,
    isNominated: false,
    videoStatus: { status: "Fail" },
    recommendation: { status: "Not Recommended" },
    phone: "010-0000-0003",
    trackPreference: "Mechanical Design",
    internships: [],
  },
  {
    id: "4",
    name: "Nour Mostafa",
    email: "nour.mostafa@guc.edu.eg",
    university: "German University in Cairo",
    major: "Mechatronics Engineering",
    gpa: 3.91,
    status: { status: "Nominated" },
    score: 95,
    isNominated: true,
    videoStatus: { status: "Pass" },
    recommendation: { status: "Strongly Recommended" },
    phone: "010-0000-0004",
    trackPreference: "Mechatronics",
    internships: [],
  },
  {
    id: "5",
    name: "Omar Sherif",
    email: "omar.sherif@alexu.edu.eg",
    university: "Alexandria University",
    major: "Computer Engineering",
    gpa: 3.34,
    status: { status: "Processing" },
    score: 71,
    isNominated: false,
    videoStatus: { status: "Pass" },
    recommendation: { status: "Recommended" },
    phone: "010-0000-0005",
    trackPreference: "Computer Engineering",
    internships: [],
  },
  {
    id: "6",
    name: "Salma Reda",
    email: "salma.reda@nu.edu.eg",
    university: "Nile University",
    major: "Biomedical Engineering",
    gpa: 3.67,
    status: { status: "Evaluated" },
    score: 84,
    isNominated: false,
    videoStatus: { status: "Pass" },
    recommendation: { status: "Recommended" },
    phone: "010-0000-0006",
    trackPreference: "Biomedical",
    internships: [],
  },
  {
    id: "7",
    name: "Karim Hassan",
    email: "karim.hassan@aucegypt.edu",
    university: "The American University in Cairo",
    major: "Computer Science",
    gpa: 3.55,
    status: { status: "Imported" },
    score: 68,
    isNominated: false,
    videoStatus: { status: "Pass" },
    recommendation: { status: "Recommended" },
    phone: "010-0000-0007",
    trackPreference: "Computer Science",
    internships: [],
  },
  {
    id: "8",
    name: "Mariam Tarek",
    email: "mariam.tarek@cu.edu.eg",
    university: "Cairo University",
    major: "Architecture Engineering",
    gpa: 3.88,
    status: { status: "Nominated" },
    score: 93,
    isNominated: true,
    videoStatus: { status: "Pass" },
    recommendation: { status: "Strongly Recommended" },
    phone: "010-0000-0008",
    trackPreference: "Architecture",
    internships: [],
  },
  {
    id: "9",
    name: "Ahmed Nabil",
    email: "ahmed.nabil@zewailcity.edu.eg",
    university: "Zewail City of Science and Technology",
    major: "Communications Engineering",
    gpa: 3.29,
    status: { status: "Processing" },
    score: 59,
    isNominated: false,
    videoStatus: { status: "Fail" },
    recommendation: { status: "Not Recommended" },
    phone: "010-0000-0009",
    trackPreference: "Communications",
    internships: [],
  },
  {
    id: "10",
    name: "Hana Wael",
    email: "hana.wael@guc.edu.eg",
    university: "German University in Cairo",
    major: "Computer Science",
    gpa: 3.72,
    status: { status: "Evaluated" },
    score: 80,
    isNominated: false,
    videoStatus: { status: "Pass" },
    recommendation: { status: "Recommended" },
    phone: "010-0000-0010",
    trackPreference: "Software Engineering",
    internships: [],
  },
];
