import type { Candidate } from "../../types/candidates";

export const candidatesMockData: Candidate[] = [
  {
    id: "1",
    name: "Mohammed Khalil",
    email: "mohammed.khalil@aucegypt.edu",
    university: "The American University in Cairo",
    major: "Computer Science",
    gpa: 3.78,
    status: { status: "Nominated" },
    score: 91,
    isNominated: true,
    videoStatus: { status: "Pass" },
    recommendation: { status: "Strongly Recommended" },
    phone: "+20 100 123 4567",
    trackPreference: "Full-Stack",
    profile: {
      graduationYear: 2027,
      skills: [
        "Java",
        "Spring Boot",
        "TypeScript",
        "React",
        "PostgreSQL",
        "Docker",
        "AWS",
        "REST APIs",
      ],
      languages: ["Arabic (Native)", "English (Fluent)"],
      projects: [
        "Built a full-stack e-commerce platform with React and Spring Boot serving 1k+ mock orders.",
        "Implemented a microservices-based ticketing system with Docker and Kubernetes.",
      ],
      experience: [
        "Summer intern at a fintech startup — maintained backend services in Java.",
        "Teaching assistant for an introductory programming course (2 semesters).",
      ],
      certifications: ["AWS Certified Cloud Practitioner"],
      extracurriculars: ["President of the university coding club."],
    },
    evaluation: {
      score: 91,
      selectionReason:
        "Top performer across technical and communication dimensions; clear nomination.",
      videoFluencyScore: 88,
      videoPresentationScore: 84,
      reportText:
        "Mohammed Khalil demonstrates strong alignment with the Software Engineering 2026 criteria. " +
        "Technical skills and project work are the primary contributors to the overall score.",
      scoreBreakdown: [
        { dimension: "Major Match", score: 95, weight: 15, contribution: 14.3 },
        {
          dimension: "Technical Skills",
          score: 92,
          weight: 25,
          contribution: 23,
        },
        { dimension: "Projects", score: 90, weight: 20, contribution: 18 },
        { dimension: "Experience", score: 85, weight: 10, contribution: 8.5 },
        {
          dimension: "Academic Performance",
          score: 93,
          weight: 15,
          contribution: 14,
        },
        {
          dimension: "Extracurriculars",
          score: 88,
          weight: 5,
          contribution: 4.4,
        },
        { dimension: "Communication", score: 90, weight: 10, contribution: 9 },
      ],
      strengths: [
        "Strong fundamentals in data structures and algorithms.",
        "Clear, well-structured technical communication.",
      ],
      weaknesses: ["Limited professional (non-academic) experience."],
      riskNotes: ["Stated availability not yet confirmed."],
    },
  },
  {
    id: "2",
    name: "Laila Fathy",
    email: "laila.fathy@cu.edu.eg",
    university: "Cairo University",
    major: "Electrical Engineering",
    gpa: 3.42,
    status: { status: "Evaluated" },
    score: 76,
    isNominated: false,
    videoStatus: { status: "Pass" },
    recommendation: { status: "Recommended" },
    phone: "+20 101 234 5678",
    trackPreference: "Embedded Systems",
    profile: {
      graduationYear: 2026,
      skills: ["C", "Embedded C", "MATLAB", "PCB Design"],
      languages: ["Arabic (Native)", "English (Fluent)"],
      projects: ["Designed a motor-control PCB for a senior design project."],
      experience: ["Intern at a power-systems consultancy."],
      certifications: [],
      extracurriculars: ["Member of the IEEE student branch."],
    },
    evaluation: {
      score: 76,
      selectionReason:
        "Solid technical grounding; academic performance and communication are mid-range.",
      videoFluencyScore: 74,
      videoPresentationScore: 71,
      reportText:
        "Laila Fathy shows competent electrical engineering fundamentals with relevant hands-on project " +
        "work. Overall profile places her in the recommended tier.",
      scoreBreakdown: [
        { dimension: "Major Match", score: 82, weight: 15, contribution: 12.3 },
        {
          dimension: "Technical Skills",
          score: 75,
          weight: 25,
          contribution: 18.75,
        },
        { dimension: "Projects", score: 72, weight: 20, contribution: 14.4 },
        { dimension: "Experience", score: 68, weight: 10, contribution: 6.8 },
        {
          dimension: "Academic Performance",
          score: 76,
          weight: 15,
          contribution: 11.4,
        },
        {
          dimension: "Extracurriculars",
          score: 70,
          weight: 5,
          contribution: 3.5,
        },
        {
          dimension: "Communication",
          score: 74,
          weight: 10,
          contribution: 7.4,
        },
      ],
      strengths: ["Relevant internship experience in power systems."],
      weaknesses: ["Limited software/programming exposure."],
      riskNotes: [],
    },
  },
  {
    id: "3",
    name: "Youssef Adel",
    email: "youssef.adel@asu.edu.eg",
    university: "Ain Shams University",
    major: "Mechanical Engineering",
    gpa: 3.15,
    status: { status: "Rejected" },
    score: 62,
    isNominated: false,
    videoStatus: { status: "Fail" },
    recommendation: { status: "Not Recommended" },
    phone: "+20 102 345 6789",
    trackPreference: "Mechanical Design",
    profile: {
      graduationYear: 2026,
      skills: ["SolidWorks", "AutoCAD", "MATLAB"],
      languages: ["Arabic (Native)"],
      projects: ["Designed a gearbox assembly for a capstone project."],
      experience: [],
      certifications: [],
      extracurriculars: [],
    },
    evaluation: {
      score: 62,
      selectionReason:
        "Below the bar on experience and communication; video assessment did not pass.",
      videoFluencyScore: 58,
      videoPresentationScore: 52,
      reportText:
        "Youssef Adel's profile shows limited professional experience and a single academic project. " +
        "The video assessment did not meet the passing threshold for communication.",
      scoreBreakdown: [
        { dimension: "Major Match", score: 70, weight: 15, contribution: 10.5 },
        {
          dimension: "Technical Skills",
          score: 60,
          weight: 25,
          contribution: 15,
        },
        { dimension: "Projects", score: 55, weight: 20, contribution: 11 },
        { dimension: "Experience", score: 30, weight: 10, contribution: 3 },
        {
          dimension: "Academic Performance",
          score: 62,
          weight: 15,
          contribution: 9.3,
        },
        {
          dimension: "Extracurriculars",
          score: 40,
          weight: 5,
          contribution: 2,
        },
        {
          dimension: "Communication",
          score: 55,
          weight: 10,
          contribution: 5.5,
        },
      ],
      strengths: ["Basic CAD proficiency."],
      weaknesses: [
        "No professional experience.",
        "Failed the video communication assessment.",
      ],
      riskNotes: [
        "Video assessment failed — recommend re-evaluation before further consideration.",
      ],
    },
  },
  {
    id: "4",
    name: "Nour Mostafa",
    email: "nour.mostafa@guc.edu.eg",
    university: "German University in Cairo",
    major: "Mechatronics Engineering",
    gpa: 3.91,
    status: { status: "Nominated" },
    score: 95,
    isNominated: true,
    videoStatus: { status: "Pass" },
    recommendation: { status: "Strongly Recommended" },
    phone: "+20 103 456 7890",
    trackPreference: "Robotics",
    profile: {
      graduationYear: 2027,
      skills: ["ROS", "Python", "C++", "SolidWorks", "Control Systems"],
      languages: [
        "Arabic (Native)",
        "German (Intermediate)",
        "English (Fluent)",
      ],
      projects: [
        "Built an autonomous line-following robot with ROS and computer vision.",
        "Led a team project on a robotic arm control system.",
      ],
      experience: ["Research assistant in a robotics lab."],
      certifications: ["Coursera Robotics Specialization"],
      extracurriculars: [
        "Captain of the university robotics competition team.",
      ],
    },
    evaluation: {
      score: 95,
      selectionReason:
        "Exceptional technical depth and leadership; top nomination candidate.",
      videoFluencyScore: 93,
      videoPresentationScore: 90,
      reportText:
        "Nour Mostafa demonstrates outstanding technical breadth across robotics and controls, backed " +
        "by strong academic performance and demonstrated leadership.",
      scoreBreakdown: [
        {
          dimension: "Major Match",
          score: 97,
          weight: 15,
          contribution: 14.55,
        },
        {
          dimension: "Technical Skills",
          score: 96,
          weight: 25,
          contribution: 24,
        },
        { dimension: "Projects", score: 95, weight: 20, contribution: 19 },
        { dimension: "Experience", score: 90, weight: 10, contribution: 9 },
        {
          dimension: "Academic Performance",
          score: 95,
          weight: 15,
          contribution: 14.25,
        },
        {
          dimension: "Extracurriculars",
          score: 94,
          weight: 5,
          contribution: 4.7,
        },
        {
          dimension: "Communication",
          score: 92,
          weight: 10,
          contribution: 9.2,
        },
      ],
      strengths: [
        "Deep robotics and controls expertise.",
        "Demonstrated team leadership.",
      ],
      weaknesses: ["No industry (non-research) internship yet."],
      riskNotes: [],
    },
  },
  {
    id: "5",
    name: "Omar Sherif",
    email: "omar.sherif@alexu.edu.eg",
    university: "Alexandria University",
    major: "Computer Engineering",
    gpa: 3.34,
    status: { status: "Processing" },
    score: 71,
    isNominated: false,
    videoStatus: { status: "Fail" },
    recommendation: { status: "Not Recommended" },
    phone: "+20 104 567 8901",
    trackPreference: "Data / ML",
  },
  {
    id: "6",
    name: "Salma Reda",
    email: "salma.reda@nu.edu.eg",
    university: "Nile University",
    major: "Biomedical Engineering",
    gpa: 3.67,
    status: { status: "Evaluated" },
    score: 84,
    isNominated: false,
    videoStatus: { status: "Pass" },
    recommendation: { status: "Recommended" },
    phone: "+20 105 678 9012",
    trackPreference: "Medical Devices",
    profile: {
      graduationYear: 2026,
      skills: ["MATLAB", "SolidWorks", "Signal Processing", "Python"],
      languages: ["Arabic (Native)", "English (Fluent)"],
      projects: ["Developed a prototype ECG signal-processing pipeline."],
      experience: ["Intern at a medical devices startup."],
      certifications: [],
      extracurriculars: [
        "Volunteer at a biomedical engineering outreach program.",
      ],
    },
    evaluation: {
      score: 84,
      selectionReason:
        "Strong project work in a specialized domain; good overall profile.",
      videoFluencyScore: 80,
      videoPresentationScore: 78,
      reportText:
        "Salma Reda shows strong applied skills in biomedical signal processing, supported by relevant " +
        "internship experience and consistent academic performance.",
      scoreBreakdown: [
        { dimension: "Major Match", score: 88, weight: 15, contribution: 13.2 },
        {
          dimension: "Technical Skills",
          score: 82,
          weight: 25,
          contribution: 20.5,
        },
        { dimension: "Projects", score: 85, weight: 20, contribution: 17 },
        { dimension: "Experience", score: 78, weight: 10, contribution: 7.8 },
        {
          dimension: "Academic Performance",
          score: 84,
          weight: 15,
          contribution: 12.6,
        },
        {
          dimension: "Extracurriculars",
          score: 80,
          weight: 5,
          contribution: 4,
        },
        {
          dimension: "Communication",
          score: 79,
          weight: 10,
          contribution: 7.9,
        },
      ],
      strengths: ["Strong applied signal-processing project."],
      weaknesses: [
        "Limited exposure to regulatory/QA aspects of medical devices.",
      ],
      riskNotes: [],
    },
  },
  {
    id: "7",
    name: "Karim Hassan",
    email: "karim.hassan@aucegypt.edu",
    university: "The American University in Cairo",
    major: "Computer Science",
    gpa: 3.55,
    status: { status: "Imported" },
    score: 68,
    isNominated: false,
    videoStatus: { status: "Fail" },
    recommendation: { status: "Not Recommended" },
    phone: "+20 106 789 0123",
    trackPreference: "Frontend",
  },
  {
    id: "8",
    name: "Mariam Tarek",
    email: "mariam.tarek@cu.edu.eg",
    university: "Cairo University",
    major: "Architecture Engineering",
    gpa: 3.88,
    status: { status: "Nominated" },
    score: 93,
    isNominated: true,
    videoStatus: { status: "Pass" },
    recommendation: { status: "Strongly Recommended" },
    phone: "+20 107 890 1234",
    trackPreference: "Design",
    profile: {
      graduationYear: 2026,
      skills: ["AutoCAD", "Revit", "SketchUp", "Rhino"],
      languages: [
        "Arabic (Native)",
        "English (Fluent)",
        "French (Intermediate)",
      ],
      projects: [
        "Designed a mixed-use development masterplan for a graduation thesis.",
        "Led a student team in a national architecture design competition.",
      ],
      experience: ["Intern at an architecture and urban planning firm."],
      certifications: [],
      extracurriculars: ["Head of the university architecture society."],
    },
    evaluation: {
      score: 93,
      selectionReason:
        "Exceptional design portfolio and leadership; strong nomination.",
      videoFluencyScore: 91,
      videoPresentationScore: 89,
      reportText:
        "Mariam Tarek presents an outstanding design portfolio backed by competition recognition and " +
        "relevant firm experience, with strong academic and communication scores.",
      scoreBreakdown: [
        { dimension: "Major Match", score: 96, weight: 15, contribution: 14.4 },
        {
          dimension: "Technical Skills",
          score: 90,
          weight: 25,
          contribution: 22.5,
        },
        { dimension: "Projects", score: 94, weight: 20, contribution: 18.8 },
        { dimension: "Experience", score: 88, weight: 10, contribution: 8.8 },
        {
          dimension: "Academic Performance",
          score: 93,
          weight: 15,
          contribution: 13.95,
        },
        {
          dimension: "Extracurriculars",
          score: 92,
          weight: 5,
          contribution: 4.6,
        },
        { dimension: "Communication", score: 90, weight: 10, contribution: 9 },
      ],
      strengths: [
        "Award-recognized design portfolio.",
        "Demonstrated leadership in student organizations.",
      ],
      weaknesses: ["Limited exposure to construction/site management."],
      riskNotes: [],
    },
  },
  {
    id: "9",
    name: "Ahmed Nabil",
    email: "ahmed.nabil@zewailcity.edu.eg",
    university: "Zewail City of Science and Technology",
    major: "Communications Engineering",
    gpa: 3.29,
    status: { status: "Processing" },
    score: 59,
    isNominated: false,
    videoStatus: { status: "Fail" },
    recommendation: { status: "Not Recommended" },
    phone: "+20 108 901 2345",
    trackPreference: "RF / Wireless",
  },
  {
    id: "10",
    name: "Hana Wael",
    email: "hana.wael@guc.edu.eg",
    university: "German University in Cairo",
    major: "Computer Science",
    gpa: 3.72,
    status: { status: "Evaluated" },
    score: 80,
    isNominated: false,
    videoStatus: { status: "Pass" },
    recommendation: { status: "Recommended" },
    phone: "+20 109 012 3456",
    trackPreference: "Backend",
    profile: {
      graduationYear: 2027,
      skills: ["Python", "Django", "PostgreSQL", "Docker"],
      languages: [
        "Arabic (Native)",
        "German (Intermediate)",
        "English (Fluent)",
      ],
      projects: [
        "Built a REST API for a university course-registration system.",
      ],
      experience: ["Backend intern at a logistics tech company."],
      certifications: [],
      extracurriculars: ["Member of the GUC coding club."],
    },
    evaluation: {
      score: 80,
      selectionReason:
        "Consistent backend skillset with relevant internship experience.",
      videoFluencyScore: 79,
      videoPresentationScore: 75,
      reportText:
        "Hana Wael demonstrates solid backend development skills and practical experience through a " +
        "relevant internship, with steady academic performance.",
      scoreBreakdown: [
        {
          dimension: "Major Match",
          score: 85,
          weight: 15,
          contribution: 12.75,
        },
        {
          dimension: "Technical Skills",
          score: 82,
          weight: 25,
          contribution: 20.5,
        },
        { dimension: "Projects", score: 78, weight: 20, contribution: 15.6 },
        { dimension: "Experience", score: 75, weight: 10, contribution: 7.5 },
        {
          dimension: "Academic Performance",
          score: 80,
          weight: 15,
          contribution: 12,
        },
        {
          dimension: "Extracurriculars",
          score: 72,
          weight: 5,
          contribution: 3.6,
        },
        {
          dimension: "Communication",
          score: 78,
          weight: 10,
          contribution: 7.8,
        },
      ],
      strengths: ["Practical backend internship experience."],
      weaknesses: ["Limited cloud/DevOps exposure."],
      riskNotes: [],
    },
  },
];
